In [1]:
set1:set = {1,1,3,3,3,5,8,7,9,10}
set1.add(11)
set1

{1, 3, 5, 7, 8, 9, 10, 11}

In [2]:
for value in set1:
    print(value)

1
3
5
7
8
9
10
11


In [6]:
import numpy as np

array1:np.ndarray = np.array(range(1,11))
array1 + 10 * 50

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510])

In [8]:
display(np.arange(1.3,3.5,0.1))
display(np.linspace(1,2,20))

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [11]:
display(np.random.random())
display(np.random.randn(10,5,3))
display(np.random.randint(1,10,size=(10,5)))

0.8007490631369087

array([[[-0.00912387,  0.92305745,  1.26573259],
        [ 0.15307411,  0.4254324 ,  0.22511681],
        [ 0.35386205, -0.37751103,  0.05820785],
        [ 0.02409856, -0.06295812, -0.25432522],
        [-0.06470644,  0.52076653, -1.26352608]],

       [[ 0.96528969, -0.58124614, -0.69322395],
        [ 0.76168316,  1.39507255, -0.15562078],
        [-1.92398302,  0.13808981,  0.62369439],
        [-0.88729145,  0.96902223,  0.72088979],
        [-1.44807069,  1.42861414, -0.6203408 ]],

       [[ 0.47583278,  1.26606414, -1.83832542],
        [ 0.71319068, -2.78680813, -1.63531001],
        [ 0.92510062,  1.2876334 , -0.2710197 ],
        [ 0.04246348, -1.15968491, -0.42417435],
        [-0.70273657, -0.96168221,  0.68640093]],

       [[ 1.25799205,  0.18881457,  1.321051  ],
        [ 0.93084622, -0.02812169, -0.32019469],
        [ 0.52552133, -2.06873329,  0.24184859],
        [ 0.85629105, -0.03057768,  0.90982082],
        [ 0.43095957,  1.12790779,  0.73878925]],

       [[-1.

array([[7, 8, 6, 7, 3],
       [2, 8, 3, 9, 1],
       [8, 7, 9, 9, 1],
       [7, 6, 5, 3, 3],
       [7, 1, 1, 6, 8],
       [9, 6, 1, 8, 2],
       [9, 6, 8, 1, 1],
       [1, 4, 7, 7, 7],
       [8, 3, 7, 9, 3],
       [8, 5, 9, 6, 5]])